server:
  port: 9090
spring:
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url : jdbc:mysql://192.168.99.100:3308/springcloud?characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root : INFO



